services:
  web:
    build: ./claudey
    container_name: acu_chat_app
    ports:
      - "8000:8000"
    volumes:
      - ./claudey:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=6zzj5#owa9ma+#u*xsq8at6o*-85u)og+9^y8rqyjyxk=*a439
      - ALLOWED_HOSTS=*
      - POSTGRES_NAME=claudey_db
      - POSTGRES_USER=claudey_db
      - POSTGRES_PASSWORD=claudeyy123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: acuchat_db
    environment:
      POSTGRES_USER: claudey_db
      POSTGRES_PASSWORD: claudeyy123
      POSTGRES_DB: claudey_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: