# Generated by Django 6.0.3 on 2026-03-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text="URL of the university's page where data was scraped.", unique=True)),
                ('title', models.CharField(help_text='Title of the page.', max_length=255)),
                ('content', models.TextField(help_text='Content of the page.')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the data was scraped.')),
            ],
            options={
                'verbose_name': 'University Data',
                'verbose_name_plural': 'University Data',
            },
        ),
    ]
