# Generated by Django 5.2.12 on 2026-03-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitydata',
            name='category',
            field=models.CharField(choices=[('program', 'Program'), ('course', 'Course'), ('general', 'General'), ('admission', 'Admission'), ('staff', 'Staff'), ('contact', 'Contact'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='universitydata',
            name='level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='universitydata',
            name='source',
            field=models.CharField(choices=[('main_site', 'Main Site'), ('bologna', 'Bologna')], default='main_site', max_length=20),
        ),
        migrations.AlterField(
            model_name='universitydata',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='universitydata',
            name='scraped_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='universitydata',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='universitydata',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
