# Generated by Django 5.2.13 on 2026-05-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_universitydata_category_universitydata_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitydata',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
